###CREATE A NEW USER
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "email@test.com",
  "password": "12345"
}

###SIGNIN AS AN EXISTING USER
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "email@test.com",
  "password": "12345"
}

### Get the currentlly signed in user
GET http://localhost:3000/auth/whoami

### SIGN OUT
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=hola@hola.com

### Remove a particular user with a given ID
DELETE http://localhost:3000/auth/1

### Update an user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
  "password": "aaa"
}